### ISSUE TITLE
hg_lengths()

### ISSUE THREAD

**Issue by stevenschumacher** [mskilab/gUtils#5] opened 2016-03-24 23:31 UTC
I can't access the function hg_seqlengths() after installing gUtils. 
hg_seqlengths() is used as parameter defaults by functions in the ffTrack, gTrack, and skidb. 
hg_seqlengths() is defined in the source file gUtils/data-raw/prep_UCSC.R, but does not end up being accessible in the package namespace.

**Comment by jwalabroad** [comment] 2016-03-25 00:36
Ahh yes. We need a new way to do this. I propose removing hg19 as a default and just require these functions to have a genome supplied directly. We could still have hg_seqlengths, but with no defaults. The problem with having a default is that if someone is using something besides hg19 someday, it would be too easy to accidentally mix something up along the line and mix their genome with hg19.

**Comment by mskilab** [comment] 2016-03-25 00:57
hmm it is quite convenient though - maybe we could allow setting of some global or environment variable that applies a default?

**Comment by stevenschumacher** [comment] 2016-03-25 07:47
I think having the reference genome as a set of global background objects with a default isn't a bad idea, despite modern software engineering precepts. That's how I retrofitted the GISTIC code to work with other organisms, because it would have been such a pain to find and replace the ubiquitous num2chromosome() and chromosome2num() calls with extra genome arguments and then plumb the entire call tree to them. R has some advantages over old entrenched Matlab code for this kind of thing, but I think the global genome as a design concept greatly reduces complexity.

**Comment by jwalabroad** [comment] 2016-03-25 13:51
OK, I agree that having a default is good-ish. I checked in a change that adds back hg_seqlengths, and allows using the default hg19. However, we should *really* not rely on this, and anytime hg19 is being used it should be specified. I think a happy medium is to use it, but throw a warning if it's getting the default instead of a provided genome. For quick and dirty code, who cares about the warning, but for examples and functions inside distributed packages, it should require a genome (e.g. BSGenome.Hsapiens.UCSC.hg19::Hsapiens)

**Comment by mskilab** [comment] 2016-03-25 14:08
well what I'm thinking would allow the user to specify a default genome .. e.g. as an environment variable representing a BSgenome package or some kind of R global variable, but if they don't, then they would need to provide it as an argument.

we could even provide a convenience function that accepts aliases e.g. set_genome('hg19') would change the environment variable to the long form of BSGenome name for hg19

if no default or no arg is provided, then we error out

**Comment by jwalabroad** [comment] 2016-03-25 14:16
Are you good with R text to command functions? something like eval(text(  etc... The issue is that we don't want to list every possible BSgenome as a dependency for the package. That was a problem with hg_seqlengths, because it only allowed two options (18 or 19), and had to do a library load for each. 

We could do something like mygenome <- eval(Sys.getenv("DEFAULT_BSGENOME")) where DEFAULT_BSGENOME is "BSgenome.Hsapiens.UCSC.hg19" etc

**Comment by mskilab** [comment] 2016-03-25 14:58
yeah that's basically what I was thinking 

I don't think we need to allow eval syntax .. but we would need to allow a library call in this situation

e.g.

genome = Sys.getenv('DEFAULT_BSGENOME')
library(genome)

for read_hg()

Is it possible to just put library calls into the package without import statements, and let the user figure out their specific dependencies?  This is just the awkward reality of how BSgenome objects are distributed (i.e. as packages)

**Comment by jwalabroad** [comment] 2016-03-25 15:05
Can't use library statements ever, won't pass CRAN. How about this:

`  if (is.null(genome)) {
    if (nchar(dbs <- Sys.getenv("DEFAULT_BSGENOME")) == 0)
      stop("hg_seqlengths: supply genome or set default with env variable DEFAULT_BSGENOME (e.g. BSgenome.Hsapiens.UCSC.hg19::Hsapiens)")
    genome = eval(parse(text=dbs))
    print(paste("hg_seqlengths: using default genome --", dbs))
  }`

**Comment by jwalabroad** [comment] 2016-03-25 17:02
Recommend adding this to your bashrc:

export DEFAULT_BSGENOME='BSgenome.Hsapiens.UCSC.hg19::Hsapiens'

**Closed by jwalabroad** 2016-03-25 17:02 UTC
